### ISSUE TITLE
missing block

### ISSUE THREAD

**Issue by fpgasdr** [ctarver/GNURadioDPD#1]
hello,
I want to evaluate the DPD for GNUradio but when open the flowgraph there is missing blocks fro DPD and don't know how to import them to GNUradio companion.

Thanks,
regards.

**Comment by ctarver** [comment]
Hi,

This project is pretty sloppy. It was kinda thrown together to get it to work in time for a publication. 

gr-Test is the module name (I was testing if I could get a custom module to work then ended up building my project there. It's terrible I know).  This has to be compiled for your system. This is a standard procedure that you can probably read about on the gnuradio documentation. It looks something like: Create a build directory. cmake. make. make install. sudo ldconfig. 

I can probably revisit this is a few weeks to make everything more understandable.

Thanks,
Chance

**Comment by fpgasdr** [comment]
Hi @ctarver ,
I was able to install the module like you says after remove the build folder and create again.
thanks for the help.

**Comment by ctarver** [comment]
Thanks for doing this! I need to go through this process too and document it properly. There should be activity on this over the summer.
